version: '{build}'
skip_tags: true

image:
  - Visual Studio 2019

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk17

before_build:
  - cmd: ./gradlew --version

build_script:
  - cmd: ./gradlew clean build -x test --info

test_script:
  - cmd: ./gradlew test koverXmlReport --info

after_test:
  - ps: |
      Write-Host 'Uploading test results to AppVeyor…'
      $wc = New-Object 'System.Net.WebClient'
      ForEach ($file in Get-ChildItem -Recurse -Include "TEST-name.valery1707*.xml") {
          $wc.UploadFile("$($env:APPVEYOR_URL)/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", $file)
      }

cache:
  - C:\Users\appveyor\.gradle\caches -> versions.lock
  - C:\Users\appveyor\.gradle\wrapper -> gradle\wrapper\gradle-wrapper.properties
