pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "base=main"
      - "#approved-reviews-by>=1"
      - "#review-threads-unresolved=0"
      - "-draft"
      - "#check-success>=10"
      - "#check-failure=0"
      - "#check-pending=0"
      - "#check-skipped=0"
      - "#check-stale=0"
      - "#check-timed-out=0"
    actions:
      merge:
        method: merge

  - name: Automatic merge for my pull requests
    conditions:
      - "base=main"
      - "-draft"
      - "author=valery1707"
      - "#check-success>=10"
      - "#check-failure=0"
      - "#check-pending=0"
      - "#check-skipped=0"
      - "#check-stale=0"
      - "#check-timed-out=0"
    actions:
      merge:
        method: merge

  - name: Automatic merge for Dependabot pull requests
    conditions:
      - "base=main"
      - "author=dependabot[bot]"
      - "#check-success>=10"
      - "#check-failure=0"
      - "#check-pending=0"
      - "#check-skipped=0"
      - "#check-stale=0"
      - "#check-timed-out=0"
    actions:
      merge:
        method: merge
