name: Build Gradle project

on: pull_request

jobs:
  build-gradle-project:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        jvmVersion: [ '17' ]
        jvmDistribution: [ 'adopt', 'zulu', 'liberica' ]
    name: Build with ${{ matrix.jvmVersion }} (${{ matrix.jvmDistribution }}) on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.jvmVersion }} (${{ matrix.jvmDistribution }})
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jvmVersion }}
          distribution: ${{ matrix.jvmDistribution }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
        run: ./gradlew check
